// src/map_editor.vue
<script setup lang="ts">
import { computed } from 'vue';
import konva from 'konva';
import { Point } from './hex';
import { useMapEditorStore } from './stores/map_editor';
import { size, origin, terrainHue } from './constants';

const store = useMapEditorStore();
const cellList = computed(() => Object.values(store.terrainData).map(d => {
  const pixel = new Point(d.x, d.y).toPixel(size).add(origin);
  const fillH = terrainHue[d.terrain] ? terrainHue[d.terrain] : 300;

  return {
    x: pixel.x,
    y: pixel.y,
    sides: 6,
    radius: size,
    fill: `hsl(${fillH}, 60%, 60%)`,
    fill1: `hsl(${fillH}, 65%, 65%)`,
    elavation: d.elavation,
    renderH1: d.elavation >= 1 || d.terrain === 3,
    renderH2: d.elavation >= 2 || d.terrain === 3,
    stroke1: `hsl(${fillH}, 50%, 50%)`,
    strokeWidth: 2,
    id: `${d.x},${d.y}`,
    originalPos: { x: d.x, y: d.y }
  };
}));

const onTileClick = (e: any) => {
  if (e.target instanceof konva.RegularPolygon) {
    const { originalPos } = e.target.attrs;
    store.setTile(originalPos);
  }
};
</script>

<template>
  <v-group name="tiles" @click="onTileClick">
    <v-group v-for="cellData in cellList" :key="cellData.id">
      <v-regular-polygon :config="cellData"></v-regular-polygon>
      <v-regular-polygon
        v-if="cellData.renderH2"
        :config="{
          x: cellData.x,
          y: cellData.y,
          sides: cellData.sides,
          radius: cellData.radius - 4,
          fill: cellData.fill1,
          stroke: cellData.stroke1,
          strokeWidth: cellData.strokeWidth + 2,
          listening: false
        }"
      ></v-regular-polygon>
      <v-regular-polygon
        v-if="cellData.renderH1"
        :config="{
          x: cellData.x,
          y: cellData.y,
          sides: cellData.sides,
          radius: cellData.radius - 8,
          fill: cellData.fill1,
          stroke: cellData.stroke1,
          strokeWidth: cellData.strokeWidth,
          listening: false
        }"
      ></v-regular-polygon>
      <v-text :config="{ x: cellData.x, y: cellData.y, text: cellData.id, listening: false }"></v-text>
    </v-group>
  </v-group>
</template>

// src/views/map_editor.tsx
import { useCallback } from 'react';
import { Group, RegularPolygon } from 'react-konva';
import { useRecoilState } from 'recoil';
import { Pos } from '../engine/hex';
import { mapEditorState } from '../stores/map_editor';
import { size, origin, elavationColor } from '../constants';
import { TerrainTile } from './components/terrain';

const MapEditor = () => {
  const [editorState, setEditorState] = useRecoilState(mapEditorState);
  const cellList = Object.keys(editorState.terrainData).map(key => ({
    ...editorState.terrainData[key],
    id: key,
  }));
  const setTile = useCallback((id: string) => {
    if (!editorState.terrainData[id]) {
      console.log('Nonsense location', id);
      return;
    }
    if (editorState.editMode === 'elavation') {
      const tile = editorState.terrainData[id];
      const newTile = {...tile, elavation: (tile.elavation + 1) % 4 };
      setEditorState({
        ...editorState,
        terrainData: {
          ...editorState.terrainData,
          id: newTile,
        },
      });
    } else if (editorState.editMode === 'terrain') {
      const tile = editorState.terrainData[id];
      const newTile = {...tile, terrain: editorState.terrainSelect };
      setEditorState({
        ...editorState,
        terrainData: {
          ...editorState.terrainData,
          id: newTile,
        },
      });
    }
  }, [editorState]);

  return (
    <Group name="tiles">
      {cellList.map((d) => {
        const pixel = Pos.add(origin, Pos.toPixel(d, size));

        return (
          <Group key={d.id} x={pixel.x} y={pixel.y} onClick={() => setTile(d.id)}>
            <RegularPolygon
              sides={6}
              radius={size}
              fill={elavationColor[d.elavation]}
              strokeWidth={2}
              name="elavation"
            />
            <TerrainTile terrain={d.terrain} />
          </Group>
        );
      })}
    </Group>
  );
};

export default MapEditor;
